name: Editor Config

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint-editorconfig:
    runs-on: ubuntu-latest
    name: 📝 Check indentation, EOL, EOF, ...
    steps:
    -  uses: actions/checkout@v6
    -  uses: editorconfig-checker/action-editorconfig-checker@v2